# Generated by Django 5.0.6 on 2024-05-27 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
