# Generated by Django 5.0.6 on 2024-05-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0002_listen_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listens.release'),
        ),
    ]
