# Generated by Django 5.0.6 on 2024-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0004_listen_json_from_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='played',
            field=models.CharField(default='NEVER', max_length=100),
            preserve_default=False,
        ),
    ]
