# Generated by Django 5.0.6 on 2024-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0005_listen_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
