# Generated by Django 5.0.6 on 2024-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0007_listen_lastfm_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
