# Generated by Django 5.0.6 on 2024-05-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0008_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='lastfm_when',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
