# Generated by Django 5.0.6 on 2024-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0009_alter_listen_lastfm_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='videoId',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
