# Generated by Django 5.0.6 on 2024-05-29 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0010_song_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
