# Generated by Django 5.0.6 on 2024-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0011_listen_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='listen',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
