# Generated by Django 5.0.6 on 2024-05-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listens', '0012_alter_listen_options_alter_listen_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['when']},
        ),
    ]
